### ISSUE TITLE
Is there a method to update a single parent Models counter?

### ISSUE THREAD

**Issue by kidbombay** [magnusvk/counter_culture#140]
I have a user with has many notifications
For performance I do a batch operation directly on a bunch of notifications
can I then call user.fix_counts? I don't want to update every User, just that specific one?

**Comment by magnusvk** [comment]
Unfortunately that doesn't currently exist. You could write one yourself; or if you were to make a pull request for this, I'd definitely look at that.

**Comment by xtagon** [comment]
I am also in need of this. My use case is a soft-deletable model: if the record is restored/undeleted, I want a callback to be fired that will fix the counter caches for just this record. Is the only way to do that presently to fix the count for all records, regardless of whether they changed or not?

**Comment by magnusvk** [comment]
@xtagon your case is really a bug in counter_culture, I'd argue: Undeletes should increment the counter just like creates. Feel free to file a separate issue or just do a pull-request. ;) (Alternatively, you could just write your own callback in your codebase.)

**Comment by xtagon** [comment]
@magnusvk I understand...I can write my own callback, but what I'm saying is that I'm not sure what that callback would look like. I know what event to hook into for my undelete framework but I'm not sure what code I can call to regenerate the counter just for this particular model, and not the whole table. You know what I mean?

**Comment by magnusvk** [comment]
Yeah, right, but why do that at all? If you're undeleting one record you know that you should just increment the counter by one, right? The way I'd want to change counter_culture is to treat `deleted_at` going from `NOT NULL` to `NULL` the same was as a create.

**Comment by xtagon** [comment]
Ah, I see what you're saying. I guess I assume there must be some caveat to the obvious solution of just incrementing the count by one, because I don't know how the internals of counter_culture look. If it's that easy I think I can implement it myself in a callback but if you are interested I'm willing to work with you on a pull request...just might need some hand holding.

**Comment by magnusvk** [comment]
Just looking at the code a bit more, it seems that we assume the `after_destroy` callback will get called when `deleted_at` gets set. But it doesn't seem to trigger `after_create` on undelete, which is probably right.

Are you using `acts_as_paranoid`? That provides an `after_restore` callback. If so, can you try using the `increment-count-on-restore` branch of this gem?

**Comment by xtagon** [comment]
I'm using [Paranoia](https://rubygems.org/gems/paranoia) which I believe is the same thing. I'll try the `increment-count-on-restore` when I get a chance. Thanks!

**Comment by magnusvk** [comment]
@xtagon I added a spec and turned this into a PR in #166. Seems to work. I'll release a gem version if you can confirm this works in real-world usage.

**Comment by Tongboy** [comment]
Can confirm PR #166 counts look good with Paranoia 2.3.0 after restore/undelete of soft deleted models

**Comment by magnusvk** [comment]
Great, I released that as gem version 1.6.0.

**Comment by abrambailey** [comment]
I tried running `user.fix_counts` and `user.counter_culture_fix_counts` and this is still not working for me. In my case I'm attempting to merge records and re-assigning some counted associations (ids change to target of the merge).

**Comment by magnusvk** [comment]
@abrambailey counter_culture doesn't support doing that on a single model. You'd have to run fix counts for the entire model, or do this manually.

**Comment by abrambailey** [comment]
@magnusvk If I just manually update the count column on the object would that have any negative impact?

**Comment by magnusvk** [comment]
No that should be fine.

**Comment by PhilCoggins** [comment]
This is a feature that I'd love to see in CounterCulture, it would improve parity with Rails' vanilla CounterCache.

As a temp workaround, I can call `Reconciliation` directly with a scope that I give it:

```
Comment.after_commit_counter_cache.each do |counter|
  CounterCulture::Reconciler::Reconciliation.new(counter, [], {}, Post.where(id: 1)).perform
end
```

@magnusvk Do you see any potential issues with calling `Reconciliation` directly? Any desire to add this feature in the future?

**Comment by magnusvk** [comment]
Probably fine, though it's not designed to be used that way. @PhilCoggins could you use the new `where` option for this? https://github.com/magnusvk/counter_culture#manually-populating-counter-cache-values

**Comment by PhilCoggins** [comment]
@magnusvk This works great, thank you!
